### ISSUE TITLE
Make messages editable 

### ISSUE THREAD

**Issue by gvNN7** [yy1300326388/loadany#1]
For internationalization purposes.. can you make the messages being passed through constructor ?

**Comment by vjunjoced** [comment]
According to the documentation you can create a function that returns the text you want to display.
`loadMoreBuilder`
```
child: LoadAny(
  onLoadMore: getLoadMore,
  ...
  loadMoreBuilder: (BuildContext context, LoadStatus status) {
    if (status == LoadStatus.loading) {
      return Container(
        height: 40,
        child: Text('Loading'),
        color: Colors.green,
        alignment: Alignment.center,
      );
    }
    return null;
  },
  child: ...
```

**Comment by gvNN7** [comment]
Thanks for your reply! 
Unfortunately i am not using this package anymore, but i think your solution should help someone in the future.
