### ISSUE TITLE
Multiple _buildLoadMore.

### ISSUE THREAD

**Issue by vjunjoced** [yy1300326388/loadany#2]
When RefreshIndicator is being used, in each update _buildLoadMore is being added to the end of the list.

I don't know if the problem is with this part of the code

```
widget.child.slivers.add(
      SliverSafeArea(
        top: false,
        left: false,
        right: false,
        sliver: SliverToBoxAdapter(
          child: _buildLoadMore(widget.status),
        ),
      ),
    );
```

![alt text](https://i.imgur.com/HGLogkB.png "img1")

**Comment by ricardkollcaku** [comment]
same here. when refresh is being used in every click a new status element is added

**Comment by BytesZero** [comment]
https://github.com/yy1300326388/loadany/blob/8a42359ed9c6d906ae44d46f0df3bd3a80d743a1/example/lib/main.dart#L42-L46

Here `if (status == LoadStatus.normal)` is very critical, I do n’t think you will operate two refreshes at the same time.

**Comment by BytesZero** [comment]
@vjunjoced @ricardkollcaku  A new version 0.1.3 has been released, you can try it, if you have any other findings, please feel free to give me feedback.

Thanks @vjunjoced  for [PR](https://github.com/yy1300326388/loadany/pull/3)

[loadany 0.1.3](https://pub.dev/packages/loadany#-changelog-tab-)
